FROM golang:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /opt

RUN apt update

COPY ../op-stack/optimism /opt/optimism
WORKDIR /opt/optimism
RUN make op-batcher

WORKDIR /opt
COPY ./scripts/start-op-batcher.sh ./scripts/
RUN chmod +x ./scripts/start-op-batcher.sh

CMD ["./scripts/start-op-batcher.sh"]


