FROM golang:latest

SHELL ["/bin/bash", "-c"]

WORKDIR /opt

RUN apt update && apt install -y jq

COPY ../op-stack/optimism /opt/optimism
WORKDIR /opt/optimism
RUN make op-proposer

WORKDIR /opt
COPY ./scripts/start-op-proposer.sh ./scripts/
RUN chmod +x ./scripts/start-op-proposer.sh

CMD ["./scripts/start-op-proposer.sh"]


